##
# Secret
# ------
# type
#  - Default key-value secret type. Eg of types are TLS Certificate etc
# data
#  - Key-value pairs where value is base64 encoded
#  - To get a base64 encoding execute: echo -n '<string>' | base64
#  - In this case it is admin/welcome1
##
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: d2VsY29tZTE=
