<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.6</version>
    <relativePath /> <!-- lookup parent from repository -->
  </parent>
  <groupId>io.github.cafeduke</groupId>
  <artifactId>dukecart</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>dukecart</name>
  <description>Duke shopping cart</description>
  <url />
  <licenses>
    <license />
  </licenses>
  <developers>
    <developer />
  </developers>
  <scm>
    <connection />
    <developerConnection />
    <tag />
    <url />
  </scm>
  <properties>
    <java.version>25</java.version>
  </properties>
  <dependencies>

    <!-- SpringBoot Security -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>

    <!-- SpringBoot OAuth2 : Resource server capabilities inside the spring boot application -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
    </dependency>

    <!-- SpringBoot JOSE : Securely transfer claims between parties -->
    <!-- Claims are JSON Web tokens/signaures/encryption/keys (JWT, JWS, JWE and JWK) -->
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-jose</artifactId>
    </dependency>

    <!-- SpringBoot JPA : Simplified CRUD using JpaRespository -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>

    <!-- SpringBoot Data Rest : REST capabilities including support of pagination, sorting and filtering -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-rest</artifactId>
    </dependency>

    <!-- MySQL database connector -->
    <dependency>
      <groupId>com.mysql</groupId>
      <artifactId>mysql-connector-j</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Automatically generate setters and getters -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- Jackson for parsing JSON -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>

    <!--
      ####################################################################################################
      Test dependencies
      ####################################################################################################
    -->

    <!-- TestNG test framework -->
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>7.11.0</version>
      <scope>test</scope>
    </dependency>

    <!-- A reporting tool for TestNG -->
    <dependency>
      <groupId>com.github.cafeduke</groupId>
      <artifactId>jreportng</artifactId>
      <version>1.3.1</version>
      <scope>test</scope>
    </dependency>

    <!-- JGet java client -->
    <dependency>
      <groupId>com.github.cafeduke</groupId>
      <artifactId>jget</artifactId>
      <version>20250423</version>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </exclude>
          </excludes>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>

        <configuration>
          <workingDirectory>${project.build.directory}</workingDirectory>
          <reportsDirectory>${project.build.directory}/jreportng</reportsDirectory>

          <systemPropertyVariables>
            <jreport.title>DukeCart Test Report</jreport.title>
            <jreport.home>${project.build.directory}/jreportng</jreport.home>
            <jreport.org.prefix>io.github.cafeduke.dukecart</jreport.org.prefix>
          </systemPropertyVariables>

          <properties>
            <property>
              <name>usedefaultlisteners</name>
              <value>false</value>
            </property>
            <property>
              <name>listener</name>
              <value>
                com.github.cafeduke.jreportng.TestListener,org.uncommons.reportng.HTMLReporter,org.uncommons.reportng.JUnitXMLReporter</value>
            </property>
          </properties>

          <suiteXmlFiles>
            <suiteXmlFile>src/test/resources/config/Suite.xml</suiteXmlFile>
          </suiteXmlFiles>

        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
