#!/bin/bash -e

# -------------------------------------------------------------------------------------------------
# Functions
# -------------------------------------------------------------------------------------------------
BASEDIR=$(dirname $(readlink -f ${0}))
BASENAME=$(basename ${0})
TOMCAT_LOGFILE="${BASEDIR}/logs/app.log"

function usage {
  echo "Start/Stop springboot using maven"
  echo "Usage: ${BASENAME} <start|stop|restart>"
}

function dieUsage {
  local mesg=${1}
  echo "Error: ${1}"
  usage
  exit 1
}

function heading {
  echo ""
  echo "---------------------------------------------------------------------------------------------------"
  for mesg in "$@"
  do
    echo "${mesg}"
  done
  echo "---------------------------------------------------------------------------------------------------"
}

function pollForMesg {
  local mesg="$1"
  local file="$2"
  local timeoutSec="${3:-10}"
  local i status=1
  for (( i = 0; i < timeoutSec; ++i ))
  do
    status=$(grep -q "$mesg" "$file")
    if [[ $status -eq 0 ]]
    then
      break
    fi
    sleep 1
  done

  if [[ $status -ne 0 ]]
  then
    dieUsage "Tomcat failed to start"
  fi
}

function log {
  local mesg="$1"
  echo "["$(date)"] $mesg"
}

function springStart {
  heading "Starting server"
  rm -f "${TOMCAT_LOGFILE}"
  mvn clean compile spring-boot:start
  log "Waiting for Tomcat to start"
  pollForMesg "Tomcat started on port" "TOMCAT_LOGFILE"
  grep "Tomcat started on port" "${TOMCAT_LOGFILE}"
  log "Logfile: ${TOMCAT_LOGFILE}"
}

function springStop {
  local pid

  heading "Stopping server"
  set +e
  mvn spring-boot:stop
  pid=$(ps -ef | grep SpringApplication | grep -v grep | awk '{print $2}')
  if [[ ! -z "${pid}" ]]
  then
    echo "Killing spring processes"
    kill -9 ${pid}
  fi
  set -e
}

# -------------------------------------------------------------------------------------------------
# Parse Arg
# -------------------------------------------------------------------------------------------------
if [[ ${#} -eq 1 && ("${1}" == "--help" || "${1}" == "-h") ]]
then
  usage
  exit 0
fi

if [[ ${#} -ne 1 ]]
then
  dieUsage "Incorrect argument count"
fi

op=${1}

# -------------------------------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------------------------------
cd ${BASEDIR}
if [[ ${op} == "start" ]]
then
  springStart
elif [[ ${op} == "stop" ]]
then
  springStop
elif [[ ${op} == "restart" ]]
then
  springStop
  springStart
else
  dieUsage "Unknown option ${op}"
fi
