# The version of the docker-compose yaml to be used
version: "3"

# The containers to be created
services: 

  # Create the redis-server container out of the image
  redis-server:
    image: "redis"

  # Build the node-app container from the current directory  
  node-app:
    build: .
    restart: on-failure
    ports:
      - "9080:8080"

